"""
Shared API schemas for cross-domain use.

These schemas define common response formats used across multiple domains.
"""

from typing import Optional

from pydantic import BaseModel, Field


class ErrorResponse(BaseModel):
    """
    Standard error response schema following RFC 7807 Problem Details format.

    This provides a consistent error envelope for application errors across all endpoints.
    """

    type: str = Field(
        ...,
        description="A URI reference that identifies the problem type",
        examples=["https://httpstatuses.com/404"],
    )
    title: str = Field(
        ...,
        description="A short, human-readable summary of the problem type",
        examples=["Not Found"],
    )
    status: int = Field(
        ...,
        description="The HTTP status code generated by the origin server for this occurrence of the problem",
        examples=[404],
    )
    detail: Optional[str] = Field(
        None,
        description="A human-readable explanation specific to this occurrence of the problem",
        examples=["Intent with ID 123 not found"],
    )
    instance: Optional[str] = Field(
        None,
        description="A URI reference that identifies the specific occurrence of the problem",
        examples=["/intents/123"],
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "type": "https://httpstatuses.com/404",
                    "title": "Not Found",
                    "status": 404,
                    "detail": "Intent with ID 123 not found",
                    "instance": "/intents/123",
                },
                {
                    "type": "https://httpstatuses.com/400",
                    "title": "Bad Request",
                    "status": 400,
                    "detail": "Invalid request payload",
                    "instance": "/intents",
                },
                {
                    "type": "https://httpstatuses.com/409",
                    "title": "Conflict",
                    "status": 409,
                    "detail": "Intent with this name already exists",
                    "instance": "/intents",
                },
            ]
        }
    }
